### ISSUE TITLE
Rest Issue

### ISSUE THREAD

**Issue by deepsarda** [discordeno/discordeno#2724]
**Describe the bug** Rest has several issues.
1. The rest is unable to send images.
2. TimeoutOverflowWarning: 1673801429763 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
    at new Timeout (node:internal/timers:168:17)
    at setTimeout (node:timers:164:19)
    at Module.setTimeout (/home/container/node_modules/@deno/shim-timers/dist/index.js:6:18)
    at Object.handleCompletedRequest (file:///home/container/node_modules/discordeno/esm/rest/createInvalidRequestBucket.js:78:44)
    at Object.sendRequest (file:///home/container/node_modules/discordeno/esm/rest/sendRequest.js:45:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.processGlobalQueue (file:///home/container/node_modules/discordeno/esm/rest/processGlobalQueue.js:6:5)
    Is a error

**Comment by Skillz4Killz** [comment]
Fixed
