### ISSUE TITLE
WebSocket not found and variables with "any" type in ws/shard.ts

### ISSUE THREAD

**Issue by MilSci** [discordeno/discordeno#300]
When using the boilerplate provided for the Discordeno bot, errors occur specifically in the `shard.ts` file - 

```
error: TS2304 [ERROR]: Cannot find name 'WebSocket'.
  ws: WebSocket;
      
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:26:7

TS2304 [ERROR]: Cannot find name 'WebSocket'.
  const ws = new WebSocket(proxyWSURL);
                 
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:48:18

TS7031 [ERROR]: Binding element 'timeStamp' implicitly has an 'any' type.
  ws.onerror = ({ timeStamp }) => {
                  
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:70:19

TS7031 [ERROR]: Binding element 'message' implicitly has an 'any' type.
  ws.onmessage = ({ data: message }) => {
                          
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:74:27

TS7031 [ERROR]: Binding element 'reason' implicitly has an 'any' type.
  ws.onclose = ({ reason, code, wasClean }) => {
                  
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:149:19

TS7031 [ERROR]: Binding element 'code' implicitly has an 'any' type.
  ws.onclose = ({ reason, code, wasClean }) => {
                          
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:149:27

TS7031 [ERROR]: Binding element 'wasClean' implicitly has an 'any' type.
  ws.onclose = ({ reason, code, wasClean }) => {
                                
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:149:33

TS2304 [ERROR]: Cannot find name 'WebSocket'.
  if (shard.ws.readyState === WebSocket.CLOSED) {
                              
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:248:31

TS2304 [ERROR]: Cannot find name 'WebSocket'.
  if (shard?.ws.readyState === WebSocket.CLOSED) {
  
    at https://deno.land/x/discordeno@10.0.0/src/ws/shard.ts:344:32
```

I assume these are errors only fixed in the `shard.ts` file but please let me know if it is user error

**Comment by MilSci** [comment]
User error, had to do `deno upgrade`
