### ISSUE TITLE
[Bug]: Why does RestManager require a token if it's being proxied?

### ISSUE THREAD

**Issue by SowTag** [discordeno/discordeno#3483]
### Runtime

Deno

### Runtime Version

1.41.2

### Version

18.0.1

### Describe the bug

The method `createRestManager()`, imported from `@discordeno/rest` always seems to require a token even if `customUrl` and `secretKey` is provided. If you use a tool like `netcat` to hook to the port where the REST manager should be, we get that the requests send the following headers:

```bash
~ nc -l 8080
GET /v10/users/@me HTTP/1.1
authorization: 1234
accept: */*
accept-language: *
user-agent: Deno/1.41.2
accept-encoding: gzip, br
host: localhost:8080
```

So, the `Authorization` header is being replaced with `secretKey` (1234 in this case for testing purposes). Why is `token` required then if it is not used in this case? Is this expected behavior?

By the way, this is not a type-checking issue, as the error arises from an if statement:

```bash
error: Uncaught (in promise) Error: The REST was not given a token. Please provide a token and try again.
  if (!token) throw new Error(`The ${type} was not given a token. Please provide a token and try again.`);
                    ^
    at removeTokenPrefix (https://deno.land/x/discordeno@18.0.1/util/token.ts:4:21)
    at createRestManager (https://deno.land/x/discordeno@18.0.1/rest/restManager.ts:29:12)
    at file:///home/*/*/src/gateway/mod.ts:9:14
    at eventLoopTick (ext:core/01_core.js:169:7)

```

### What should've happened?

`token` shouldn't be required if `customUrl` AND `secretKey` are both present.

### Code to reproduce the bug

```typescript
// @discordeno is import-aliased to https://deno.land/x/discordeno@18.0.1/mod.ts
// in deno.json
import { createRestManager } from '@discordeno'

const REST = createRestManager({
    secretKey: 'super secret key here',
    customUrl: 'http://localhost:8080'
});

const user = await REST.runMethod(REST, 'GET', '/users/@me');
console.log(user)

// Throws error as token is missing here.
```

**Comment by SowTag** [comment]
Closed. v19 provides a better explanation:

```ts
import { createRestManager } from 'npm:@discordeno/rest'

const REST = createRestManager({
  customUrl: 'http://localhost:8080',
  secretKey: '1234'
});

console.log(REST)

// => error: Uncaught (in promise) Error: `applicationId` was not provided and was not able to extract the id from the bots token. Please explicitly pass `applicationId` to the rest manager.
```
